name: helloWorld

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/*"
  pull_request:
     branches: [main]
  repository_dispatch:
    types: ["after_rendered_cms"]

jobs:
  echo-vars:
   runs-on: ubuntu-latest
   steps:
    - name: Echo Github Variable
      run: 
       echo "trigger by ${{github.event_name}}"
       echo "repo by ${{github.repository}}"
       echo "ref-name by ${{github.ref_name}}"

  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Hello GitHub Actions."
        
      - name: Retrive c p l
        run: echo "Client Send Status ':' ${{github.event.client_Payload.status}}"
             echo "Client Send Statoos ':' ${{github.event.client_Payload.statoos}}"


  second-job:
    runs-on: windows-latest
    needs: hello-job

    steps:
      - run: echo "This job running on ${{ runner.os }}"
